  
# <font color=gray>第3章 数据预处理</font>
## <font color=gray>3.1 numpy基础
### 　<font color=gray>3.1.1 向量
### 　<font color=gray>3.1.2 数组
#### 　　　<font color=gray>3.1.2.1 数据类型与结构数组
#### 　　　<font color=gray>3.1.2.2 索引与切片
#### 　　　<font color=gray>3.1.2.3 数组的属性
#### 　　　<font color=gray>3.1.2.4 数组排序
#### 　　　<font color=gray>3.1.2.5 数组维度
#### 　　　3.1.2.6 数组组合
#### 　　　3.1.2.7 数组分拆
#### 　　　3.1.2.8 ufunc运算
###### 　　　　1.标准函数
###### 　　　　2.自定义函数
###### 　　　　3.广播
###### 　　　　4.方法
### 　3.1.3 矩阵
### 　3.1.4 文件读写

#### 　　　3.1.2.6 数组组合

In [ ]:
'''
numpy的数组组合可以分为：
-- 水平组合(hstack)
-- 垂直组合(vstack)
-- 深度组合(dstack)
-- 列组合(column_stack)
-- 行组合(row_stack)
'''

In [ ]:
'''
1.水平组合：
即把所有参加组合的数组拼接起来，各数组行数应当相等。
0 0 0     1 1 1 1 1
0 0 0     1 1 1 1 1
第2个数组的列追加到第1个数组列右侧。
'''

In [1]:
import numpy as np
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
b=np.array([[0,11,22,33],[44,55,66,77],[88,99,0,11]])
print(b)

[[ 0 11 22 33]
 [44 55 66 77]
 [88 99  0 11]]


In [3]:
'''
本函数的参数只有一个，应当把要参加组合的数组对象以元组的形式作为参数。
'''
np.hstack((a,b))

array([[ 0,  1,  2,  0, 11, 22, 33],
       [ 3,  4,  5, 44, 55, 66, 77],
       [ 6,  7,  8, 88, 99,  0, 11]])

In [4]:
'''
本函数的参数只有一个，应当把要参加组合的数组对象以元组的形式作为参数。
'''
np.hstack(a,b)

TypeError: hstack() takes 1 positional argument but 2 were given

In [5]:
'''
如果参加组合的各数组的行不一致，则系统会提示错误信息。
'''
c=np.array([[0,11,22],[44,55,66],[88,99,0],[22,33,44]])
print(c)

[[ 0 11 22]
 [44 55 66]
 [88 99  0]
 [22 33 44]]


In [6]:
'''
如果参加组合的各数组的行不一致，则系统会提示错误信息。
'''
np.hstack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

总结：行数一致，以元组形式给出参数。

In [ ]:
'''
2.垂直组合：
即把所有参加组合的数组追加在一起，各数组列数应一致。
如果参加组合的各数组的列不一致，则系统会提示错误信息。
0 0 0
0 0 0 

1 1 1
1 1 1
1 1 1
第2个数组的行追加到第1个数组的行后面。
'''

In [84]:
np.vstack((a,c))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0, 11, 22],
       [44, 55, 66],
       [88, 99,  0],
       [22, 33, 44]])

In [ ]:
'''
numpy.concatenate 函数用于沿指定轴连接相同形状的两个或多个数组。
numpy.concatenate((a1, a2, ...), axis)

a1, a2, ...：相同类型的数组
axis：沿着它连接数组的轴，默认为 0
'''

In [8]:
np.concatenate((a,c),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0, 11, 22],
       [44, 55, 66],
       [88, 99,  0],
       [22, 33, 44]])

In [7]:
np.concatenate((a,c))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0, 11, 22],
       [44, 55, 66],
       [88, 99,  0],
       [22, 33, 44]])

In [9]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  0, 11, 22, 33],
       [ 3,  4,  5, 44, 55, 66, 77],
       [ 6,  7,  8, 88, 99,  0, 11]])

In [ ]:
#课堂练习1：
#生成以下三个全0、全1和全2的数组，数组名分别为k1 、k2和k3
0 0 0     1 1 1 1   2 2 2 2 
0 0 0     1 1 1 1   2 2 2 2 
                    2 2 2 2 
#要求利用np.hstack np.vstack和np.concatenate完成两数组的水平和垂直组合。

In [39]:
k1=np.zeros((2,3),dtype=int)
k1

array([[0, 0, 0],
       [0, 0, 0]])

In [40]:
k2=np.ones((2,4),dtype=int)
k2

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [41]:
k3=np.ones((3,4),dtype=int)+1
k3

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [42]:
#水平
np.hstack((k1,k2))

array([[0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1]])

In [43]:
np.concatenate((k1,k2),axis=1)

array([[0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1]])

In [44]:
#垂直
np.vstack((k2,k3))

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [45]:
np.concatenate((k2,k3),axis=0)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
'''
3.深度组合：
即将参加组合的各数组相同位置的数据合在一起。
要求所有数组维度属性要相同，类似于数组叠加。
0 0 0   1 1 1
0 0 0   1 1 1
叠加后2个数组就有2列。
'''

In [46]:
np.dstack((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [ ]:
'''
numpy.delete 函数返回从输入数组中删除指定子数组的新数组。

numpy.delete(arr, obj, axis)

arr：输入数组
obj：可以是整数、整数数组或切片，对应的是删除某行/列，不连续的某几行/列，连续的某几行/列。
axis：沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开
'''

In [10]:
abc = np.arange(12).reshape(3,4)
print (abc)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
#删除某一个元素
print ('未传递 Axis 参数。 在删除之前输入数组会被展开。')
print (np.delete(abc,5))

未传递 Axis 参数。 在删除之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]


In [12]:
#删除某几个元素，可以是连续的，也可以是不连续的。
abc = np.arange(12)
print (np.delete(abc,[1,3,5,7,9,11]))

[ 0  2  4  6  8 10]


In [13]:
print ('包含从数组中删除的替代值的切片：')
abc = np.arange(12)
print (np.delete(abc,[1:12:2]))#通过切片指定删除的子数组a[1:9:2]

SyntaxError: invalid syntax (<ipython-input-13-e21e161b0633>, line 3)

In [14]:
print ('包含从数组中删除的替代值的切片：')
abc = np.arange(12)
print (np.delete(abc, np.s_[1:12:2]))#通过切片指定删除的子数组a[1:9:2]

包含从数组中删除的替代值的切片：
[ 0  2  4  6  8 10]


In [2]:
import numpy as np
help(np.s_)

Help on IndexExpression in module numpy.lib.index_tricks object:

class IndexExpression(builtins.object)
 |  A nicer way to build up index tuples for arrays.
 |  
 |  .. note::
 |     Use one of the two predefined instances `index_exp` or `s_`
 |     rather than directly using `IndexExpression`.
 |  
 |  For any index combination, including slicing and axis insertion,
 |  ``a[indices]`` is the same as ``a[np.index_exp[indices]]`` for any
 |  array `a`. However, ``np.index_exp[indices]`` can be used anywhere
 |  in Python code and returns a tuple of slice objects that can be
 |  used in the construction of complex index expressions.
 |  
 |  Parameters
 |  ----------
 |  maketuple : bool
 |      If True, always returns a tuple.
 |  
 |  See Also
 |  --------
 |  index_exp : Predefined instance that always returns a tuple:
 |     `index_exp = IndexExpression(maketuple=True)`.
 |  s_ : Predefined instance without tuple conversion:
 |     `s_ = IndexExpression(maketuple=False)`.
 |  
 |  N

In [52]:
abc = np.arange(12).reshape(3,4)
print ('删除第二列：')
print (np.delete(abc,1,axis = 1))

删除第二列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [53]:
#删除数组abc的第二、三列。
abc = np.arange(12).reshape(3,4)
print ('删除第二、三列：')
print (np.delete(abc,[1,2],axis = 1))

删除第二、三列：
[[ 0  3]
 [ 4  7]
 [ 8 11]]


In [54]:
#删除数组abc的前三列。
abc = np.arange(12).reshape(3,4)
print ('删除前三列：')
print (np.delete(abc,np.s_[0:3],axis = 1))

删除前三列：
[[ 3]
 [ 7]
 [11]]


In [55]:
#删除数组abc的第二行。
abc = np.arange(12).reshape(3,4)
print ('删除第二行：')
print (np.delete(abc,1,axis =0))

删除第二行：
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [ ]:
#课堂练习：删除数组b的最后一列生成数组d，完成ad深度组合。

In [56]:
d=np.delete(b,3,axis=1)
print(d)

[[ 0 11 22]
 [44 55 66]
 [88 99  0]]


In [57]:
#深度组合后数组形状（3，3，2），
#两个数组的各行元素组成了各层元素，行数决定了层数
#列数决定行数
#组合数组的个数决定列数
np.dstack((a,d))

array([[[ 0,  0],
        [ 1, 11],
        [ 2, 22]],

       [[ 3, 44],
        [ 4, 55],
        [ 5, 66]],

       [[ 6, 88],
        [ 7, 99],
        [ 8,  0]]])

In [ ]:
#课堂练习：完成k1、k2的深度组合

In [58]:
k4=np.delete(k2,3,axis=1)
print(k4)

[[1 1 1]
 [1 1 1]]


In [59]:
np.dstack((k1,k4))

array([[[0, 1],
        [0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1],
        [0, 1]]])

In [5]:
'''
4.列组合(左右拼接)
-- 对于一维数组按列方向进行组合，不是简单的追加列。
   而是两个数组中相同位置的元素叠加，维度由1维增加为2维。
   元素个数决定新数组行，数组个数决定新数组列
-- 对于二维数组，column_stack与hstack（追加列）效果相同
'''
a1=np.arange(4)
a2=np.arange(4)*2
print(a1)
print("**********************")
print(a2)
#a3=np.arange(4)
np.column_stack((a1,a2))

[0 1 2 3]
**********************
[0 2 4 6]


array([[0, 0],
       [1, 2],
       [2, 4],
       [3, 6]])

In [6]:
a1=np.arange(4).reshape(2,2)
a2=(np.arange(4)*2).reshape(2,2)
print(a1)
print("**********************")
print(a2)
np.column_stack((a1,a2))

[[0 1]
 [2 3]]
**********************
[[0 2]
 [4 6]]


array([[0, 1, 0, 2],
       [2, 3, 4, 6]])

In [7]:
'''
5.行组合（row_stack）(上下拼接)
-- 对于一维数组按行方向组合（追加行），维度由1维增加为2维。
-- 对于二维数组，与vstack效果相同（追加行）。

'''
a1=np.arange(4)
a2=np.arange(4)*2
print(a1)
print("**********************")
print(a2)
np.row_stack((a1,a2))#第一个数组是第一行，第二个数组是第二行。

[0 1 2 3]
**********************
[0 2 4 6]


array([[0, 1, 2, 3],
       [0, 2, 4, 6]])

In [8]:
a1=np.arange(4).reshape(2,2)
a2=(np.arange(4)*2).reshape(2,2)
print(a1)
print("**********************")
print(a2)
np.row_stack((a1,a2))

[[0 1]
 [2 3]]
**********************
[[0 2]
 [4 6]]


array([[0, 1],
       [2, 3],
       [0, 2],
       [4, 6]])

#### 　　　3.1.2.7 数组分拆

In [ ]:
'''
-- 水平分拆（hsplit）
-- 垂直分拆（vsplit）
-- 深度分拆（dsplit）
-- 各种分拆（split）
数据分拆的结果是一个由数组作为元素构成的列表。
'''

In [62]:
'''
1.水平分拆：沿着水平方向进行分拆，纵向按列拆。
数据分拆结果返回的是列表，而列表中的元素才是numpy数组。
'''
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [63]:
ahs=np.hsplit(a,3)#数组的列数应该能整除拆分的个数
print(ahs)

[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


In [64]:
type(ahs)

list

In [65]:
type(ahs[1])

numpy.ndarray

In [ ]:
'''
2.垂直分拆：
vsplit和split函数均可实现把数组沿着垂直方向进行分拆的功能，横向按行拆。
'''

In [24]:
np.vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [ ]:
'''
numpy.split 函数沿特定的轴将数组分割为子数组

numpy.split(ary, indices_or_sections, axis)

ary：被分割的数组
indices_or_sections：如果是一个整数，就用该数平均切分，
                     如果是一个数组，为沿轴切分的位置（左闭右开）
axis：沿着哪个维度进行切分，默认为0，横向切分。为1时，纵向切分
'''

In [68]:
#split函数水平分拆，按列拆
np.split(a,3,axis=1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [69]:
#split函数垂直分拆，按行拆
np.split(a,3,axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [67]:
help(np.split)

Help on function split in module numpy.lib.shape_base:

split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays.
    
    Parameters
    ----------
    ary : ndarray
        Array to be divided into sub-arrays.
    indices_or_sections : int or 1-D array
        If `indices_or_sections` is an integer, N, the array will be divided
        into N equal arrays along `axis`.  If such a split is not possible,
        an error is raised.
    
        If `indices_or_sections` is a 1-D array of sorted integers, the entries
        indicate where along `axis` the array is split.  For example,
        ``[2, 3]`` would, for ``axis=0``, result in
    
          - ary[:2]
          - ary[2:3]
          - ary[3:]
    
        If an index exceeds the dimension of the array along `axis`,
        an empty sub-array is returned correspondingly.
    axis : int, optional
        The axis along which to split, default is 0.
    
    Returns
    -------
    sub-arrays : list of nd

In [9]:
x=np.arange(8.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [70]:
'''
3.深度分拆：
按照深度方向分拆3个维度以上（含）的数组：
'''
ads=np.arange(12)
ads.shape=(2,2,3)
ads

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [71]:
help(np.dsplit)

Help on function dsplit in module numpy.lib.shape_base:

dsplit(ary, indices_or_sections)
    Split array into multiple sub-arrays along the 3rd axis (depth).
    
    Please refer to the `split` documentation.  `dsplit` is equivalent
    to `split` with ``axis=2``, the array is always split along the third
    axis provided the array dimension is greater than or equal to 3.
    
    See Also
    --------
    split : Split an array into multiple sub-arrays of equal size.
    
    Examples
    --------
    >>> x = np.arange(16.0).reshape(2, 2, 4)
    >>> x
    array([[[  0.,   1.,   2.,   3.],
            [  4.,   5.,   6.,   7.]],
           [[  8.,   9.,  10.,  11.],
            [ 12.,  13.,  14.,  15.]]])
    >>> np.dsplit(x, 2)
    [array([[[  0.,   1.],
            [  4.,   5.]],
           [[  8.,   9.],
            [ 12.,  13.]]]),
     array([[[  2.,   3.],
            [  6.,   7.]],
           [[ 10.,  11.],
            [ 14.,  15.]]])]
    >>> np.dsplit(x, np.array([3, 6]))
  

In [72]:
np.dsplit(ads,3)#按列分拆成3个3维数组。

[array([[[0],
         [3]],
 
        [[6],
         [9]]]), array([[[ 1],
         [ 4]],
 
        [[ 7],
         [10]]]), array([[[ 2],
         [ 5]],
 
        [[ 8],
         [11]]])]

In [ ]:
#课堂练习：利用np.hsplit、np.vsplit和np.split完成数组c的水平和垂直分拆。

In [25]:
#水平分拆
c=np.array([[0,11,22],[44,55,66],[88,99,0],[22,33,44]])
print(c)
np.hsplit(c,3)

[[ 0 11 22]
 [44 55 66]
 [88 99  0]
 [22 33 44]]


[array([[ 0],
        [44],
        [88],
        [22]]), array([[11],
        [55],
        [99],
        [33]]), array([[22],
        [66],
        [ 0],
        [44]])]

In [75]:
np.split(c,3,axis=1)

[array([[ 0],
        [44],
        [88],
        [22]]), array([[11],
        [55],
        [99],
        [33]]), array([[22],
        [66],
        [ 0],
        [44]])]

In [76]:
#垂直分拆
np.vsplit(c,4)

[array([[ 0, 11, 22]]),
 array([[44, 55, 66]]),
 array([[88, 99,  0]]),
 array([[22, 33, 44]])]

In [77]:
np.split(c,4,axis=0)

[array([[ 0, 11, 22]]),
 array([[44, 55, 66]]),
 array([[88, 99,  0]]),
 array([[22, 33, 44]])]

#### 　　　3.1.2.8 ufunc运算

In [1]:
'''
ufunc(universal function)是一种能对数组中每个元素进行操作的函数。
这些函数可以进行四则运算、比较运算以及布尔运算等。
numpy内置的许多ufunc函数计算速度非常快。
可以使用“out=”关键字来指定把函数返回结果存储在指定数组中。
可以使用frompyfunc函数自定义ufunc函数。
'''
import numpy as np

In [11]:
'''
1.函数运算、比较运算与布尔运算
'''
#函数运算
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a2=np.arange(0,20,2)
a2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
a3=np.add(a1,a2,out=a1)
print(a3)
print(a1)

[ 0  3  6  9 12 15 18 21 24 27]
[ 0  3  6  9 12 15 18 21 24 27]


In [31]:
'''
使用out关键字指定数组与通常使用赋值方式得到的函数运算结果数组是绑定到同一个对象的
'''
id(a3)==id(a1)

True

In [ ]:
#比较运算

In [32]:
a1>a2 #比较两个数组中的元素，返回值是数组。

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
#布尔运算

In [6]:
#比较两个数组而不是其中的元素，可以做一次与运算，所有元素为True，输出为True。
np.all(a1>a2)

False

In [7]:
#可以做一次或运算,任意一个元素为True，输出为True。
np.any(a1>a2)

True

In [33]:
'''
numpy的ufunc运算要比python内置函数运算速度快（在第3.1小节中本书已经展示过），如
给定相同的一系列元素，使得每个元素都求平方，比较二者的运算速度。
'''
def mathcal(n):
    s=[]
    for i in range(n+1):
        s.append(i**2)
    return

def ufuncal(n):
    s=np.array(range(n+1))**2
    return

%timeit mathcal(1000000)
%timeit ufuncal(1000000)

328 ms ± 12.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
135 ms ± 3.37 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [34]:
'''
2.自定义ufunc函数
通过numpy提供的标准ufunc函数，可以组合出复杂的表达式，但有些时候，用户需要自定义
函数对数组元素进行操作，这时可以用frompyfunc函数将一个计算单个元素的函数转换成
ufunc函数。

frompyfunc(func,nin,nout)

nin： 函数输入参数的个数
nout：函数返回值的个数

如在考试中，由于出题难度偏大，需要对所有人的分数进行提升，并且保持分数的相对
位置不变，可以编制一个函数：
'''
import numpy as np
def liftscore(n):
    n_new=np.sqrt((n^2)*100)
    return n_new

score=np.array([87,77,56,100,60])
#使用frompyfunc将其自定义为ufunc函数，并对数组对象进行操作
score_1=np.frompyfunc(liftscore,1,1)(score)
score_1

array([92.19544457292888, 88.88194417315589, 76.15773105863909,
       100.99504938362078, 78.74007874011811], dtype=object)

In [35]:
score_1.dtype #使用frompyfunc转换的ufunc函数所返回数组的元素类型是object

dtype('O')

In [36]:
'''
需要再调用数组的astype方法将其转换为浮点数组。
'''
score_1=score_1.astype(float)
score_1.dtype

dtype('float64')

In [37]:
score_1

array([ 92.19544457,  88.88194417,  76.15773106, 100.99504938,
        78.74007874])

In [38]:
'''
使用vectorize也可以实现和frompyfunc类似的功能。但它可以通过otypes参数指定返回
数组的元素类型。
otypes参数可以是一个表示元素类型的字符串，也可以是一个类型列表，
使用列表可以描述多个返回数组的元素类型：
'''
score_2=np.vectorize(liftscore,otypes=[float])(score)
score_2

array([ 92.19544457,  88.88194417,  76.15773106, 100.99504938,
        78.74007874])

In [39]:
score_1==score_2

array([ True,  True,  True,  True,  True])

In [40]:
np.all(score_1==score_2)

True

In [ ]:
#练习：自定义一个函数完成圆面积的计算，例如给定一组半径值[3,2,4，6]输出对应的圆面积。

In [51]:
'''
3.广播
当使用ufunc函数对两个数组进行计算时，ufunc函数会对这两个数组的对应元素进行计算。
因此要求这两个数组的形状相同。
'''
x = np.array([[2,2,3],[1,2,3]])
y = np.array([[1,1,3],[2,2,4]])
print(x)
print('------------------------')
print(y)
print('------------------------')
print(x+y)  #numpy当中的数组相加是对应元素的相加。

[[2 2 3]
 [1 2 3]]
------------------------
[[1 1 3]
 [2 2 4]]
------------------------
[[3 3 6]
 [3 4 7]]


In [ ]:
'''
3.1 广播的引出：
-- 当两个数组的形状并不相同的时候，我们可以通过扩展数组的方法来实现相加、相减、
   相乘等操作，这种机制叫做广播（broadcasting）。
    
3.2 广播发生的情况：
-- 两个数组的维数不相等，但是它们的后缘维度的轴长相符。
-- 两个数组维数相等，两个数组中某一维度轴长相同，任一数组中另一维度轴长为1。
-- 以上两种情况的混合。
-- 如果两个数组的后缘维度（即从末尾开始算起的维度）的轴长度相符或者其中一方的长度为1
  （注：这里是指两个数组同时从低维开始一一的比较，不能把其中一个数组的末尾第一个维度
    和第二个数组的末尾第二维度比较，只能是同时比较各自的末尾第一个），则可认为他们是
    广播兼容的。广播会在缺失或长度为１的维度上进行。
    
3.3 广播的原则：
-- 广播会在缺失和（或）长度为1的维度上进行。
-- 输出数组(即计算结果的数组)的shape属性是输入数组的shape属性在各个轴上的最大值。

'''

In [ ]:
# 情况1：两个数组的维数不相等，但是它们的后缘维度的轴长相符。
#例3.1（4，3）和（3，）

　　arr1的shape为（4,3），arr2的shape为（3，）,前者是二维的，而后者是一维的。
但是它们的后缘维度相等，arr1的第二维长度为3，和arr2的维度相同。
arr1和arr2的shape并不一样，但是它们可以执行相加操作，这就是通过广播完成的。
在这个例子当中是将arr2沿着0轴进行扩展。
<img src="images/broad1.png" >

In [52]:
#情况1：两个数组的维数不相等，但是它们的后缘维度的轴长相符。
#例3.1（4，3）和（3，）
import numpy as np
arr1 = np.array([[0, 0, 0],[1, 1, 1],[2, 2, 2], [3, 3, 3]])  #arr1.shape = (4,3)
arr2 = np.array([1, 2, 3])    #arr2.shape = (3,)
arr_sum = arr1 + arr2
print(arr1)
print('------------------------')
print(arr2)
print('------------------------')
print(arr_sum)

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]
------------------------
[1 2 3]
------------------------
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
#例3.2 (3,4,2)和(4,2)

<img src="images/broad2.png" width="50%">
（3,4,2）和（4,2）的维度是不相同的，前者为3维，后者为2维。但是它们后缘维度的轴长相同，都为（4,2），所以可以沿着0轴进行广播。

In [53]:
#例3.2 (3,4,2)和(4,2)
brr1=np.arange(24).reshape(3,4,2)
brr1

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [54]:
brr2=np.arange(8).reshape(4,2)
brr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [37]:
brr3=brr1+brr2
brr3

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]],

       [[ 8, 10],
        [12, 14],
        [16, 18],
        [20, 22]],

       [[16, 18],
        [20, 22],
        [24, 26],
        [28, 30]]])

In [55]:
#同样（3，4，2）和（2，）是兼容的，后者需要在两个轴上面进行扩展。
#例3.3（3,4,2）和（2，）
brr4=np.array([0,1])
brr4

array([0, 1])

In [39]:
brr5=brr1+brr4
brr5

array([[[ 0,  2],
        [ 2,  4],
        [ 4,  6],
        [ 6,  8]],

       [[ 8, 10],
        [10, 12],
        [12, 14],
        [14, 16]],

       [[16, 18],
        [18, 20],
        [20, 22],
        [22, 24]]])

In [ ]:
#情况2：两个数组维数相等，有一方的长度为1。
#例3.4 （4，3）和（4，1）

crr1的shape为（4,3），crr2的shape为（4,1），它们都是二维的，但是第二个数组在1轴上的长度为1，所以，可以在1轴上面进行广播。
<img src="images/broad3.png" width="50%">
在这种情况下，两个数组的维度要保证相等，其中有一个轴的长度为1，这样就会沿着长度为1的轴进行扩展。<br>
这样的例子还有：（4,3）和（1,3） 。<br>
（3,4,2）和（1,4,2）沿着0轴。<br>
（3,4,2）和（3,1,2）沿着1轴。<br>
（3,4,2）和（3,4,1）沿着2轴。<br>

In [ ]:
#编写程序验证（3,4,2）和（1,4,2）

In [56]:
#例3.4（4,3）和（4,1）
crr1 = np.array([[0, 0, 0],[1, 1, 1],[2, 2, 2], [3, 3, 3]])  #crr1.shape = (4,3)
crr2 = np.array([[1],[2],[3],[4]])    #crr2.shape = (4, 1)
crr3 = crr1 + crr2
print(crr1)
print('----------------------')
print(crr2)
print('----------------------')
print(crr3)

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]
----------------------
[[1]
 [2]
 [3]
 [4]]
----------------------
[[1 1 1]
 [3 3 3]
 [5 5 5]
 [7 7 7]]


In [41]:
#例3.5 （5，2）和（5，1）
a=np.arange(0,10).reshape(5,2);a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [42]:
b=np.arange(0,1,0.2).reshape(5,1);b

array([[0. ],
       [0.2],
       [0.4],
       [0.6],
       [0.8]])

In [43]:
c=a+b;c

array([[0. , 1. ],
       [2.2, 3.2],
       [4.4, 5.4],
       [6.6, 7.6],
       [8.8, 9.8]])

In [44]:
c.shape

(5, 2)

In [45]:
#例3.6（4,3）和（1,3）
crr4=np.array([1,2,3]) 
crr4

array([1, 2, 3])

In [46]:
crr5=crr1+crr4
crr5

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [47]:
#例3.7（3,4,2）和（1,4,2）
brr1

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [48]:
drr1=np.arange(8).reshape(1,4,2)
drr1

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [49]:
drr2=brr1+drr1
drr2

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]],

       [[ 8, 10],
        [12, 14],
        [16, 18],
        [20, 22]],

       [[16, 18],
        [20, 22],
        [24, 26],
        [28, 30]]])

In [ ]:
#例3.8(3,4,2）和（3,1,2）
drr3=np.arange(6).reshape(3,1,2)
drr3

In [ ]:
drr4=brr1+drr3
drr4

In [ ]:
#例3.9（3,4,2）和（3,4,1）
drr5=np.arange(12).reshape(3,4,1)
drr5

In [ ]:
drr6=brr1+drr5
drr6

In [ ]:
#情况3：
'''
以上两种情况的结合，在TensorFlow当中计算张量的时候也是用广播机制，
并且和numpy的广播机制是一样的。
'''
#例3.10（3,4,2）和（1,2）
drr7=np.array([1,2])
drr7

In [ ]:
drr8=brr1+drr7
drr8

In [ ]:
#课堂练习（5，3）和（5，2） （2，3）和（3，1）

In [ ]:
#其他情况会出错（5，3）和（5，2）
a=np.arange(0,15).reshape(5,3);a

In [ ]:
b=np.arange(0,20,2).reshape(5,2);b

In [ ]:
c=b+a;c

In [20]:
#(2,3)和（3,1）
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
b=np.arange(3).reshape(3,1)
b

array([[0],
       [1],
       [2]])

In [22]:
c=a+b
c

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [ ]:
'''
3.4 ogrid函数
广播在numpy计算中比较常见，所以numpy提供了ogrid和mgrid来创建广播计算的数组，
前者返回的是两个向量，后者返回的是进行广播运算的数组。

ogrid函数作为产生numpy数组与numpy的arange函数功能有点类似，不同的是：
-- arange函数产生的是一维数组，而ogrid函数产生的是二维数组。
-- arange函数产生的是一个数组，而ogrid函数产生的是二个数组。
-- ogrid函数产生的数组，第一个数组是以纵向产生的，即数组第二维的大小始终为1。
                        第二个数组是以横向产生的，即数组第一维的大小始终为1。
-- ogrid和多维数组一样，用切片元组作为下标。
'''

In [2]:
'''
有两个参数，返回列表，列表元素由x[0]和x[1]两个数组组成。 

第一个数组x[0]是列向量,行数由第一个参数决定（0 1 2 3 4），共五行，；
第二个数组x[1]是行向量,列数由第二个参数决定（0 1 2 3 4），共五列，；
默认步长为1，左闭右开。

第一个数组x[0]的元素由第一个参数决定（0 1 2 3 4），共五种元素；
第二个数组x[1]的元素由第二个参数决定（0 1 2 3 4），共五种元素。
'''
x=np.ogrid[:5,:5]
x

[array([[0],
        [1],
        [2],
        [3],
        [4]]), array([[0, 1, 2, 3, 4]])]

In [3]:
x,y=np.ogrid[:5,:5]#基于位置把右侧的两个数组依次赋值给左侧的元组变量。
x

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [4]:
y

array([[0, 1, 2, 3, 4]])

In [ ]:
'''
3.5 mgrid函数
mgrid对象的用法和ogrid对象类似，但它返回进行广播之后的数组。

np.mgrid[start:stop:step]

参数解析：
start:开始坐标
stop:结束坐标（实数不包括，复数包括）
step:步长：
     步长为复数表示点数，左闭右闭
     步长为实数表示间隔，左闭右开
     如：mgrid[1:3:3j, 4:9:2]  
     3j：3个点，用3个数值来等分整个区间[1,3]。

用法：返回多维结构，常见的如2D图形，3D图形。
第1返回值为第1维数据在最终结构中的分布，
第2返回值为第2维数据在最终结构中的分布，以此类推。（分布以矩阵形式呈现）  
'''

In [5]:
#有一个参数，生成一维数组，用5个数值等分区间[-5,5]。
x=np.mgrid[-5:5:5j]
x

array([-5. , -2.5,  0. ,  2.5,  5. ])

In [6]:
'''
有两个参数，返回三维空间向量，由z[0]和z[1]两个数组组成。 
两个数组的行数由第一个参数决定（0 1 2 3 4），共五行；
          列数由第二个参数决定（0 1 2 3 4），共五列；
          默认步长为1，左闭右开。

第一个数组z[0]的元素由第一个参数决定（0 1 2 3 4），共五种元素；
第二个数组z[1]的元素由第二个参数决定（0 1 2 3 4），共五种元素。

第一个数组z[0]的元素行相同；
第二个数组z[1]的元素列相同。
'''
z=np.mgrid[:5,:5]
z

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [7]:
x1=np.mgrid[:5,:3]
x1

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [8]:
x2,x3=np.mgrid[:5,:3]
x2

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [9]:
x3

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
'''
4.ufunc的方法
ufunc函数还有只对两个输入一个输出的ufunc函数有效的方法:
-- reduce
-- accumulate
-- reduceat
-- outer
'''


In [10]:
'''
4.1 reduce方法
它沿着axis轴对数组元素进行操作,相当于将相应的操作放到该轴元素之间,默认0轴。
'''
np.add.reduce(np.arange(5)) 

10

In [11]:
np.add.reduce([[1,2,3,4],[5,6,7,8]],axis=1)

array([10, 26])

In [12]:
np.add.reduce([[1,2,3,4],[5,6,7,8]],axis=0)

array([ 6,  8, 10, 12])

In [13]:
np.add.reduce([[1,2,3,4],[5,6,7,8]])

array([ 6,  8, 10, 12])

In [ ]:
'''
4.2 accumulate方法
返回的数组和输入的数组的形状相同，同时保存所有中间结果。
'''

In [15]:
np.add.accumulate(np.arange(5))

array([ 0,  1,  3,  6, 10], dtype=int32)

In [16]:
np.add.accumulate([[1,2,3,4],[5,6,7,8]],axis=1)

array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26]], dtype=int32)

In [17]:
np.add.accumulate([[1,2,3,4],[5,6,7,8]],axis=0)

array([[ 1,  2,  3,  4],
       [ 6,  8, 10, 12]], dtype=int32)

In [ ]:
'''
4.3 reduceat方法
可通过indices参数指定多对reduce的起始和终止位置，从而计算多组reduce的结果。
'''

In [18]:
ara=np.arange(8)
ara

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
np.add.reduceat(ara,indices=[0,4,1,5,2,6,3,7])

array([ 6,  4, 10,  5, 14,  6, 18,  7], dtype=int32)

In [ ]:
'''
返回数组中的元素实际上是按照如下方式进行的：
ara[0]+ara[1]+ara[2]+ara[3]=0+1+2+3=6
ara[4]=4
ara[1]+ara[2]+ara[3]+ara[4]=1+2+3+4=10
ara[5]=5
ara[2]+ara[3]+ara[4]+ara[5]=2+3+4+5=14
ara[6]=6
ara[3]+ara[4]+ara[5]+ara[6]=3+4+5+6=18
ara[7]=7
'''

In [20]:
np.add.reduceat(ara,[0,4,1,5,2,6,3,7])[::2]

array([ 6, 10, 14, 18], dtype=int32)

In [21]:
'''
4.4 outer方法
可对其作为两个参数的数组的每两对元素的组合进行运算：
'''
np.add.outer([1,2,3,4],[5,6,7,8])

array([[ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12]])

In [22]:
np.add.outer([1,2,3,4],[5,6,7])

array([[ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11]])

In [23]:
np.multiply.outer([1,2,3,4],[5,6,7,8])

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

### 　3.1.3 矩阵(matrix)

In [24]:
'''
矩阵是numpy提供的另外一种数据类型，可以使用mat或matrix函数将数组转化为矩阵。
一般情况下在python中都会使用数组来进行运算，因为数组更灵活、速度更快。
'''
m1=np.mat([[1,2,3],[4,5,6]])
m1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [25]:
m1*8

matrix([[ 8, 16, 24],
        [32, 40, 48]])

In [26]:
m2=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
m2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [27]:
m1*m2

matrix([[30, 36, 42],
        [66, 81, 96]])

In [28]:
m2.I    #m2的逆矩阵

matrix([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
        [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
        [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

### 　3.1.4 文件读写

In [ ]:
'''
通常通过以下I/O函数实现：
-- savetxt:将数组保存到文本文件。
-- loadtxt:将保存到txt文件中的数据读出为ndarrary类型。
   主要读取csv格式的文件，自动切分字段，并将数组载入numpy数组
'''

In [29]:
import os
os.getcwd()

'C:\\jupyter'

In [57]:
%pwd

'C:\\jupyter'

In [30]:
np.savetxt('m2.txt',m2) #将上面定义的m2对象作为m2.txt存储在当前文件夹中

In [31]:
'''
读入数据时要注意源文件中数据之间的分隔符，在loadtxt函数中可以使用delimiter
参数来指定
'''
m2_reload=np.loadtxt('m2.txt',delimiter=' ')
m2_reload

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [33]:
'''
如有某公司的历史股票价格数据存储在一个名为"data.csv"文档中，
将其读入numpy中作为一个数组对象。
'''
#自定义结构类型
stock=np.dtype([('name',np.str_,4),
                ('time',np.str_,10),
                ('opening_price',np.float64),
                ('closing_price',np.float64),
                ('lowest_price',np.float64),
                ('highest_price',np.float64),
                ('volume',np.int32)])
#利用自定义的结构类型，初始化结构化数组，即解释数组所占的内存。
jd_stock=np.loadtxt('data/data.csv',delimiter=',',dtype=stock)
jd_stock

array([('JD', '3-Jan-17', 25.95, 25.82, 25.64, 26.11,  8275300),
       ('JD', '4-Jan-17', 26.05, 25.85, 25.58, 26.08,  7862800),
       ('JD', '5-Jan-17', 26.15, 26.3 , 26.05, 26.8 , 10205600),
       ('JD', '6-Jan-17', 26.3 , 26.27, 25.92, 26.41,  6234300),
       ('JD', '9-Jan-17', 26.64, 26.26, 26.14, 26.95,  8071500),
       ('JD', '10-Jan-17', 26.3 , 26.9 , 26.25, 27.1 , 20417400),
       ('JD', '11-Jan-17', 26.76, 26.77, 26.44, 27.18,  5498100),
       ('JD', '12-Jan-17', 26.83, 26.61, 26.48, 26.83,  4867700),
       ('JD', '13-Jan-17', 26.77, 26.84, 26.52, 26.9 ,  5929700),
       ('JD', '17-Jan-17', 26.82, 27.21, 26.71, 27.65,  7717500),
       ('JD', '18-Jan-17', 27.34, 27.16, 26.86, 27.5 ,  5974400),
       ('JD', '19-Jan-17', 27.3 , 27.75, 27.13, 27.84, 10279700),
       ('JD', '20-Jan-17', 27.96, 27.6 , 27.54, 28.14,  7142000),
       ('JD', '23-Jan-17', 27.5 , 28.18, 27.46, 28.27,  9972400),
       ('JD', '24-Jan-17', 28.5 , 28.54, 28.22, 28.91, 13843200),
       ('JD', '