  
# <font color=gray>第3章 数据预处理</font>
## <font color=gray>3.1 numpy基础
### 　<font color=gray>3.1.1 向量
### 　<font color=gray>3.1.2 数组
#### 　　　<font color=gray>3.1.2.1 数据类型与结构数组
#### 　　　<font color=gray>3.1.2.2 索引与切片
#### 　　　3.1.2.3 数组的属性
#### 　　　3.1.2.4 数组排序
#### 　　　3.1.2.5 数组维度

#### 　　　3.1.2.3 数组的属性(见教材p94)

In [1]:
import numpy as np
ac=np.arange(12)
ac.shape=(2,2,3)
ac

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [48]:
#1.返回数组的形状，如行、列、层等。
ac.shape

(2, 2, 3)

In [49]:
#2.返回数组中各元素的类型
ac.dtype

dtype('int32')

In [2]:
goodslist=np.dtype([('name',np.str_,50),('location',np.str_,30),('price',np.float32),
                   ('volume',np.int32)])
goods=np.array([('Gree Airconditioner','JD.com',6245,1),
                ('Sony Blueray Player','Amazon.com',3210,2),
                ('Apple Macbook Pro 13','Tmall.com',12388,5),
                ('iPhoneSE','JD.com',4588,2)],dtype=goodslist)
goods.dtype

dtype([('name', '<U50'), ('location', '<U30'), ('price', '<f4'), ('volume', '<i4')])

In [55]:
#3.返回数组的维数或数组轴的个数（有多少对[]就有多少维数）
ac.ndim

3

In [56]:
#4.返回数组元素的总个数
ac.size

12

In [57]:
#5.返回数组元素在内存中所占的字节数
ac.itemsize

4

In [58]:
#6.返回数组所占的存储空间即itemsize*size
ac.nbytes

48

In [ ]:
#7.返回数组的转置数组

In [8]:
np.array([0,1,2,3]).T #数组对象.T,一维数组转置后元素值不变。

array([0, 1, 2, 3])

In [36]:
b=np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [37]:
b.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [6]:
print(ac.T)

[[[ 0  6]
  [ 3  9]]

 [[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]]


In [7]:
#转置后ac源数组形状不变
ac

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
#课堂练习1：修改ac数组中三个元素的值为100

In [10]:
ac[0,0,1]=100
ac

array([[[  0, 100,   2],
        [  3,   4,   5]],

       [[  6,   7,   8],
        [  9,  10,  11]]])

In [11]:
ac[0,1,0]=100
ac

array([[[  0, 100,   2],
        [100,   4,   5]],

       [[  6,   7,   8],
        [  9,  10,  11]]])

In [12]:
ac[1,1,2]=100
ac

array([[[  0, 100,   2],
        [100,   4,   5]],

       [[  6,   7,   8],
        [  9,  10, 100]]])

In [ ]:
#8.flat方法返回一个numpy.flatiter对象，即展平迭代器，
#可以像遍历一维数组一样遍历任意多维数组，也可获取指定元素。

In [39]:
ac=np.arange(12)
ac.shape=(2,2,3)#彻底修改，源数组形状发生改变
ac

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [6]:
ac=np.arange(12)
b=ac.reshape(2,2,3) #临时修改，源数组形状不变
ac

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
acf=ac.flat
acf

In [41]:
for i in acf:
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

In [42]:
acf[1]=100
for i in acf:
    print(i,end=' ')

0 100 2 3 4 5 6 7 8 9 10 11 

In [9]:
acf[5:]

array([ 5,  6,  7,  8,  9, 10, 11])

In [19]:
acf[1,3,11]=100
acf

IndexError: unsupported iterator index

In [43]:
#修改指定位置元素
acf[[1,3,11]]=100
print(ac)

[[[  0 100   2]
  [100   4   5]]

 [[  6   7   8]
  [  9  10 100]]]


#### 　　　3.1.2.4 数组排序

In [ ]:
'''
1.使用sort()函数

numpy.sort() 函数返回输入数组的排序副本，会分配内存保存。

numpy.sort(a, axis, kind, order)

a: 要排序的数组，强制参数
axis: int or None, 可选参数
      沿着它排序数组的轴 
      如果没有,数组在排序前会被展平
      默认值是-1, 沿着最后的轴排序
      axis=0 按列排序，axis=1 按行排序 
kind: 排序的算法，默认为'quicksort'（快速排序），可选参数
order: 如果数组包含字段，则是要排序的字段，可选参数
'''

在二维NumPy数组中，轴是沿行和列的方向


<img src="images/pic1.png" width="50%">

axis 0轴是沿着行（rows）的方向，在NumPy数组中，axis 0是第一轴。
对于二维或多维数组，axis 0是沿行（row）向下的轴。
<img src="images/pic2.png" width="50%">

axis 1轴是沿着列（columns）的方向，在NumPy数组中，axis1是第2根轴。
对于二维或多维数组，axis1是沿列（columns）横穿的轴。
<img src="images/pic3.png" width="50%">

在带有axis参数的二维数组上使用聚合函数时，它会将二维数组折叠为一维数组。
axis参数控制哪个轴将被折叠。
将NumPy和函数与axis参数一起使用时，指定的轴是折叠的轴。
<img src="images/pic4.png" width="50%">

<img src="images/pic5.png" width="50%">

一维NumPy数组只有一个轴（即axis=0）
<img src="images/pic6.png" width="40%">

In [12]:
s=np.array([1,2,4,3,1,2,2,4,6,7,2,4,8,4,5])
np.sort(s) #np.函数名

array([1, 1, 2, 2, 2, 2, 3, 4, 4, 4, 4, 5, 6, 7, 8])

In [13]:
s

array([1, 2, 4, 3, 1, 2, 2, 4, 6, 7, 2, 4, 8, 4, 5])

In [23]:
#如何倒序排列？
np.sort(-s)

array([-8, -7, -6, -5, -4, -4, -4, -4, -3, -2, -2, -2, -2, -1, -1])

In [14]:
#2 使用numpy.argsort() 函数
#此函数返回的是数组值从小到大的索引值。
np.argsort(s)

array([ 0,  4,  1,  5,  6, 10,  3,  2,  7, 11, 13, 14,  8,  9, 12],
      dtype=int32)

In [5]:
#倒序排列
np.argsort(-s)

array([12,  9,  8, 14,  2,  7, 11, 13,  3,  1,  5,  6, 10,  0,  4],
      dtype=int32)

In [15]:
#argsort() 函数返回的是数组值从大到小的索引值。
#通过升序索引值间接取出S中的元素达到升序输出的目的。
s[np.argsort(s)]

array([1, 1, 2, 2, 2, 2, 3, 4, 4, 4, 4, 5, 6, 7, 8])

In [16]:
#argsort() 函数返回的是数组值从大到小的索引值。
#通过降序索引值间接取出S中的元素达到降序输出的目的。
s[np.argsort(-s)]

array([8, 7, 6, 5, 4, 4, 4, 4, 3, 2, 2, 2, 2, 1, 1])

In [ ]:
'''
ndarray对象的sort方法可对数组进行原地排序，即改变原数组元素的位置。
'''

In [17]:
s=np.array([1,2,4,3,1,2,2,4,6,7,2,4,8,4,5])
s

array([1, 2, 4, 3, 1, 2, 2, 4, 6, 7, 2, 4, 8, 4, 5])

In [18]:
s.sort()  #对象名.方法名
print(s)

[1 1 2 2 2 2 3 4 4 4 4 5 6 7 8]


In [26]:
#3 多维数组按照数组的轴进行排序
s_r=np.array([3,23,52,34,52,3,6,645,34,7,85,23]).reshape(6,2)#reshape就地改形状
s_r

array([[  3,  23],
       [ 52,  34],
       [ 52,   3],
       [  6, 645],
       [ 34,   7],
       [ 85,  23]])

In [27]:
#3.1 按1轴排序（按行排序）
#调用方法时括号里不需要给出数组对象名称，axis=1横穿列等价于按行排序。
#每一行各排各的，互不影响
s_r.sort(axis=1)
s_r

array([[  3,  23],
       [ 34,  52],
       [  3,  52],
       [  6, 645],
       [  7,  34],
       [ 23,  85]])

In [28]:
#3.2 按0轴排序（按列排序）
#调用方法时括号里不需要给出数组对象名称，axis=0沿着行向下排序，等价于按列排序。
#每一列各排各的，互不影响
s_r=np.array([3,23,52,34,52,3,6,645,34,7,85,23]).reshape(6,2)#reshape就地改形状
s_r.sort(axis=0) 
s_r

array([[  3,   3],
       [  6,   7],
       [ 34,  23],
       [ 52,  23],
       [ 52,  34],
       [ 85, 645]])

In [ ]:
#3.3 按默认轴排序
#调用方法时括号里不需要给出数组对象名称。
#axis=-1按最后一个轴即axis 1轴，横穿列按行排序。

In [29]:
s_r=np.array([3,23,52,34,52,3,6,645,34,7,85,23]).reshape(6,2)#reshape就地改形状
s_r.sort() 
s_r

array([[  3,  23],
       [ 34,  52],
       [  3,  52],
       [  6, 645],
       [  7,  34],
       [ 23,  85]])

In [30]:
'''
4.使用lexsort函数：
此函数可以指定排序的顺序
numpy.lexsort() 用于对多个序列进行排序。
把它想象成对电子表格进行排序，每一列代表一个序列，排序时优先照顾靠后的列。
比如卓越班录取学生按照总成绩录取，在总成绩相同时，数学成绩高的优先录取，
在总成绩和数学成绩都相同时，按照英语成绩录取。
因此总成绩排在电子表格的最后一列，数学成绩在倒数第二列，英语成绩在倒数第三列。
'''
a=[1,5,1,4,3,4,4]
b=[9,4,0,4,0,2,1]
ind=np.lexsort((b,a))# 传入np.lexsort的是一个tuple，先按a排序，再按b排序，升序
ind # np.lexsort返回值是一维数组，数组元素为排序后的两个序列中每对值的索引号

array([2, 0, 4, 6, 5, 3, 1], dtype=int32)

In [34]:
for i in ind:
    print (a[i],b[i])

1 0
1 9
3 0
4 1
4 2
4 4
5 4


In [35]:
[(a[i],b[i]) for i in ind]#列表推导式取出ind中的元素

[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]

#### 　　　3.1.2.5 数组维度

In [ ]:
'''
数组的维度可以进行变换，如行列互换、降维等。
-- reshape()函数用来改变数组的维数，即不改变数据的条件下修改形状。
-- ravel()、flatten()函数可把数组展平为一维数组。

'''

In [33]:
'''
1.展平
即把多维数组降成一维数组。
'''
b=np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [35]:
b.ndim

3

In [36]:
'''
1.1 使用ravel()函数
numpy.ravel() 展平数组元素，返回的是数组视图（view），和原数组共用一块内存，
修改会影响原始数组。

numpy.ravel(a, order='C')

a: 要展平的数组，强制参数
order：可选参数
       'C' -- 按行，'F' -- 按列，
       'A' -- 原顺序，'K' -- 元素在内存中的出现顺序。
'''
br=np.ravel(b)
br

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [37]:
br[0]=100
b

array([[[100,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [42]:
'''
1.2 使用flatten()方法
ndarray对象的flatten方法与ravel函数功能相同。
但是执行flatten方法后，会分配内存保存结果，
ravel函数只是返回数组的一个视图。
'''
b=np.arange(24).reshape(2,3,4)
print(b)
bf=b.flatten()
print(bf)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [43]:
bf[0]=100
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [44]:
'''
1.3 使用reshape()函数
使用reshape函数展平后的数组维度与ravel函数展平结果的数组维度不一样。
'''
b=np.arange(24).reshape(2,3,4)
print(b)
brsh=b.reshape(1,1,24)
brsh

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23]]])

In [45]:
brsh.ndim

3

In [51]:
'''
2.维度改变
reshape方法和resize方法均可改变数组的维度和数组尺寸。
'''
#2.1 使用reshape方法：
b=np.arange(24).reshape(2,3,4)
bd=b.reshape(4,6)
bd

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [47]:
bd.ndim

2

In [52]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [53]:
#2.2 为数组的shape属性赋值：
b.shape=(1,1,24)
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23]]])

In [45]:
#2.3 使用resize方法：
'''
resize方法与reshape方法的功能一样，但是reshape只是返回数组的一个视图；
而resize会直接修改所操作的数组，与直接为数组的shape属性赋值一样。
'''
b=np.arange(24).reshape(2,3,4)
print(b)
print('----------------------------')
b.resize(1,1,24)
b

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
----------------------------


array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23]]])

In [33]:
#2.3 使用resize方法：
'''
resize方法与reshape方法的功能一样，但是reshape只是返回数组的一个视图；
而resize会直接修改所操作的数组，与直接为数组的shape属性赋值一样。
'''
b=np.arange(24).reshape(2,3,4)
print(b)
print('--------------------------')
b.reshape(1,1,24)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--------------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [46]:
#课堂练习2：输出转置后的b数组。
#3.转置：
#3.1使用transpose()函数
b=np.arange(24).reshape(2,3,4)
print(b)
b.shape=(3,4,2)
b

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [58]:
np.transpose(b) #等价于b.T

array([[[ 0,  8, 16],
        [ 2, 10, 18],
        [ 4, 12, 20],
        [ 6, 14, 22]],

       [[ 1,  9, 17],
        [ 3, 11, 19],
        [ 5, 13, 21],
        [ 7, 15, 23]]])

In [60]:
# 3.2 使用数组T属性：
b.T 

array([[[ 0,  8, 16],
        [ 2, 10, 18],
        [ 4, 12, 20],
        [ 6, 14, 22]],

       [[ 1,  9, 17],
        [ 3, 11, 19],
        [ 5, 13, 21],
        [ 7, 15, 23]]])